name: "Bug Report :bug:"
title: "Título - Descrição Resumida"
description: "Reporte de problemas e funcionalidades não conforme"
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        ## Instruções
        Antes de enviar um novo problema, siga a lista de verificação e tente encontrar a resposta:

        - Leia a documentação (Wiki) e verifique se o problema já foi abordado.
        - Certifique-se de que seu firmware está atualizado para a versão mais recente.
        - Busque por issues semelhantes no Git antes de criar uma nova.
        - Consulte a equipe de desenvolvimento e/ou manutenção para verificar se já há conhecimento ou solução para o problema.

  - type: markdown
    attributes:
      value: |
        ## Problema

  - type: textarea
    id: description
    attributes:
      label: Descrição do Problema
      description: |
        Aqui deve ser descrito de forma detalhada o problema.
    validations:
      required: true

  - type: textarea
    id: behavior
    attributes:
      label: Comportamento Esperado
      description: |
        Descreva aqui o comportamento que você espera.
    validations:
      required: true

  - type: textarea
    id: real
    attributes:
      label: Comportamento Real
      description: |
        Descreva aqui o que de fato ocorreu.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Para Reproduzir
      description: Forneça as etapas detalhadas para reproduzir o problema.
      placeholder: |
        1. Descreva o primeiro passo
        2. Explique o segundo passo
        3. Continue até o erro ser reproduzido
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Ambiente

  - type: input
    id: firm-version
    attributes:
      label: Versão de Firmware
      description: Nome e versão do firmware onde o problema ocorreu.
      placeholder: briseII - 01.01.00001
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Modelo do dispositivo
      description: Modelo do dispositivo onde o problema ocorreu.
      placeholder: Brise II

  - type: markdown
    attributes:
      value: |
        ## Desenvolvimento

  - type: textarea
    id: logs
    attributes:
      label: Logs de Debug
      description: Se possível e relevante, inclua os logs.
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Informações Complementares
    validations:
      required: false

  - type: input
    id: mcu-model
    attributes:
      label: Modelo do Microcontrolador
      value: ESP32-WROOM-32E-N8
  
  - type: input
    id: compiler
    attributes:
      label: Versão do Compilador
      value: IDF 5.4.0